# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://antojos.cl
title: Antojitos
email: ventas@antojos.cl
author: Antojitos Ahumados Limitada
description: > # "Write an awesome description for your new site here. 
  Antojitos es una pasteleria dedicada a la calidad y servicio al restaurantes,
  cafaterias y almecenes.  Vendimos tortas enteras por mayor.
copyright: '&copy; 2017 Antojitos Ahumados Limitada.'
credits: 'Credits: <a href="http://jekyllthemes.org/themes/landing-page/" target="_blank">Landing Page</a> is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/" target="_blank">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/antojitosahumados
  - title: facebook
    url: https://www.facebook.com/AntojitosAhumados
  - title: twitter
    url: https://twitter.com/AntojitoAhumado
